// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ClinicaOdontologica.API.Migrations
{
    [DbContext(typeof(ClinicaOdontologicaAPIContext))]
    [Migration("20260925022007_V01")]
    partial class V01
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClinicaOdontologica.Modelos.Cita", b =>
                {
                    b.Property<int>("idCita")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_cita");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idCita"));

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("fechaCita")
                        .HasColumnType("timestamp")
                        .HasColumnName("fecha_cita");

                    b.Property<int>("idConsultorio")
                        .HasColumnType("integer")
                        .HasColumnName("id_consultorio");

                    b.Property<int>("idOdontologo")
                        .HasColumnType("integer")
                        .HasColumnName("id_odontologo");

                    b.Property<int>("idPaciente")
                        .HasColumnType("integer")
                        .HasColumnName("id_paciente");

                    b.Property<string>("motivo")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.HasKey("idCita");

                    b.HasIndex("idConsultorio");

                    b.HasIndex("idOdontologo");

                    b.HasIndex("idPaciente");

                    b.ToTable("Citas");
                });

            modelBuilder.Entity("ClinicaOdontologica.Modelos.Consultorio", b =>
                {
                    b.Property<int>("idConsultorio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_consultorio");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idConsultorio"));

                    b.Property<string>("equipamientoPrincipal")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("equipamiento_principal");

                    b.Property<string>("numeroSala")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("numero_sala");

                    b.Property<int>("piso")
                        .HasColumnType("integer");

                    b.HasKey("idConsultorio");

                    b.ToTable("Consultorios");
                });

            modelBuilder.Entity("ClinicaOdontologica.Modelos.DetalleCita", b =>
                {
                    b.Property<int>("idDetalleCita")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_detalle_cita");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idDetalleCita"));

                    b.Property<decimal>("costoAplicado")
                        .HasColumnType("numeric(10, 2)")
                        .HasColumnName("costo_aplicado");

                    b.Property<int>("idCita")
                        .HasColumnType("integer")
                        .HasColumnName("id_cita");

                    b.Property<int>("idTratamiento")
                        .HasColumnType("integer")
                        .HasColumnName("id_tratamiento");

                    b.Property<string>("observaciones")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.HasKey("idDetalleCita");

                    b.HasIndex("idCita");

                    b.HasIndex("idTratamiento");

                    b.ToTable("DetallesCita");
                });

            modelBuilder.Entity("ClinicaOdontologica.Modelos.Especialidad", b =>
                {
                    b.Property<int>("idEspecialidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_especialidad");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idEspecialidad"));

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasColumnName("descripcion");

                    b.Property<string>("nombreEspecialidad")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre_especialidad");

                    b.HasKey("idEspecialidad");

                    b.ToTable("Especialidades");
                });

            modelBuilder.Entity("ClinicaOdontologica.Modelos.Factura", b =>
                {
                    b.Property<int>("idFactura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_factura");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idFactura"));

                    b.Property<string>("estadoPago")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("estado_pago");

                    b.Property<DateTime>("fechaEmision")
                        .HasColumnType("timestamp")
                        .HasColumnName("fecha_emision");

                    b.Property<int>("idCita")
                        .HasColumnType("integer")
                        .HasColumnName("id_cita");

                    b.Property<decimal>("impuestos")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("impuestos");

                    b.Property<decimal>("subtotal")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("total")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("total");

                    b.HasKey("idFactura");

                    b.HasIndex("idCita")
                        .IsUnique();

                    b.ToTable("Facturas");
                });

            modelBuilder.Entity("ClinicaOdontologica.Modelos.HistorialMedico", b =>
                {
                    b.Property<int>("idHistorialMedico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_historial");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idHistorialMedico"));

                    b.Property<string>("alergias")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("alergias");

                    b.Property<string>("enfermedadesPrevias")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("enfermedades_previas");

                    b.Property<int>("idPaciente")
                        .HasColumnType("integer")
                        .HasColumnName("id_paciente");

                    b.Property<string>("tipoSangre")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("tipo_sangre");

                    b.HasKey("idHistorialMedico");

                    b.HasIndex("idPaciente")
                        .IsUnique();

                    b.ToTable("HistorialesMedicos");
                });

            modelBuilder.Entity("ClinicaOdontologica.Modelos.Odontologo", b =>
                {
                    b.Property<int>("idOdontologo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_odontologo");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idOdontologo"));

                    b.Property<string>("apellidos")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("idEspecialidad")
                        .HasColumnType("integer")
                        .HasColumnName("id_especialidad");

                    b.Property<string>("nombres")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("registroMedico")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("registro_medico");

                    b.HasKey("idOdontologo");

                    b.HasIndex("idEspecialidad");

                    b.ToTable("Odontologos");
                });

            modelBuilder.Entity("ClinicaOdontologica.Modelos.Paciente", b =>
                {
                    b.Property<int>("idPaciente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_paciente");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idPaciente"));

                    b.Property<string>("apellidos")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("apellidos");

                    b.Property<string>("dni")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("dni");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<DateOnly>("fechaNacimiento")
                        .HasColumnType("date")
                        .HasColumnName("fecha_nacimiento");

                    b.Property<string>("nombres")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombres");

                    b.Property<string>("telefono")
                        .IsRequired()
                        .HasColumnType("varchar(15)")
                        .HasColumnName("telefono");

                    b.HasKey("idPaciente");

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("ClinicaOdontologica.Modelos.Receta", b =>
                {
                    b.Property<int>("idReceta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_receta");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idReceta"));

                    b.Property<DateOnly>("fechaEmision")
                        .HasColumnType("date")
                        .HasColumnName("fecha_emision");

                    b.Property<int>("idCita")
                        .HasColumnType("integer")
                        .HasColumnName("id_cita");

                    b.Property<string>("indicaciones")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("text")
                        .HasColumnName("indicaciones");

                    b.HasKey("idReceta");

                    b.HasIndex("idCita");

                    b.ToTable("Recetas");
                });

            modelBuilder.Entity("ClinicaOdontologica.Modelos.Tratamiento", b =>
                {
                    b.Property<int>("idTratamiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_tratamiento");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idTratamiento"));

                    b.Property<decimal>("costoBase")
                        .HasColumnType("numeric(10, 2)")
                        .HasColumnName("costo_base");

                    b.Property<TimeOnly>("duracionEstimadaMinutos")
                        .HasColumnType("time without time zone")
                        .HasColumnName("duracion_estimada_minutos");

                    b.Property<string>("nombreTratamiento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre_tratamiento");

                    b.HasKey("idTratamiento");

                    b.ToTable("Tratamientos");
                });

            modelBuilder.Entity("ClinicaOdontologica.Modelos.Cita", b =>
                {
                    b.HasOne("ClinicaOdontologica.Modelos.Consultorio", "Consultorio")
                        .WithMany()
                        .HasForeignKey("idConsultorio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicaOdontologica.Modelos.Odontologo", "Odontologo")
                        .WithMany()
                        .HasForeignKey("idOdontologo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicaOdontologica.Modelos.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("idPaciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consultorio");

                    b.Navigation("Odontologo");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("ClinicaOdontologica.Modelos.DetalleCita", b =>
                {
                    b.HasOne("ClinicaOdontologica.Modelos.Cita", "Cita")
                        .WithMany()
                        .HasForeignKey("idCita")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicaOdontologica.Modelos.Tratamiento", "Tratamiento")
                        .WithMany("DetallesCita")
                        .HasForeignKey("idTratamiento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cita");

                    b.Navigation("Tratamiento");
                });

            modelBuilder.Entity("ClinicaOdontologica.Modelos.Factura", b =>
                {
                    b.HasOne("ClinicaOdontologica.Modelos.Cita", "Cita")
                        .WithOne("Facturas")
                        .HasForeignKey("ClinicaOdontologica.Modelos.Factura", "idCita")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cita");
                });

            modelBuilder.Entity("ClinicaOdontologica.Modelos.HistorialMedico", b =>
                {
                    b.HasOne("ClinicaOdontologica.Modelos.Paciente", "Paciente")
                        .WithOne("HistorialMedico")
                        .HasForeignKey("ClinicaOdontologica.Modelos.HistorialMedico", "idPaciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("ClinicaOdontologica.Modelos.Odontologo", b =>
                {
                    b.HasOne("ClinicaOdontologica.Modelos.Especialidad", "Especialidad")
                        .WithMany()
                        .HasForeignKey("idEspecialidad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Especialidad");
                });

            modelBuilder.Entity("ClinicaOdontologica.Modelos.Receta", b =>
                {
                    b.HasOne("ClinicaOdontologica.Modelos.Cita", "Cita")
                        .WithMany()
                        .HasForeignKey("idCita")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cita");
                });

            modelBuilder.Entity("ClinicaOdontologica.Modelos.Cita", b =>
                {
                    b.Navigation("Facturas");
                });

            modelBuilder.Entity("ClinicaOdontologica.Modelos.Paciente", b =>
                {
                    b.Navigation("HistorialMedico");
                });

            modelBuilder.Entity("ClinicaOdontologica.Modelos.Tratamiento", b =>
                {
                    b.Navigation("DetallesCita");
                });
#pragma warning restore 612, 618
        }
    }
}
